### ISSUE TITLE
Ek özellikler

### ISSUE THREAD

**Issue by gkhnvrs** [sokrates/sokrates#2]
-> Konuya üst rütbeli (admin,mod) biri cevap verdiğinde konuda bunun bir işaret, renk ile belirtilmesi.
-> 2-3 Dil seçeneği
-> Konu kalite sayacı
-> Görüntülenme ve cevap sayısı
-> En iyi cevap seçeneği
-> Sosyal Medya'da paylaş butonları
-> Üstteki cevaptan alıntı yapma
-> Yorum beğenme
-> Özel mesaj
-> En çok soru alan etiketlerin listelenmesi(#programlama, #php)
-> Yorum raporlama
-> Yeni açılan, en çok etkileşim alan ve cevap verilmemiş konuların üç sekmede ayrılması

**Comment by selmansamet** [comment]
Bildirim için teşekkürler :tada:
Bu özellikler dikkate alınacaktır, fakat şuan temel bileşenler bile henüz oluşturulmadı.

Buradaki bahsettiğin konseptleri, daha geniş olarak tartışmamız gerekecek. Çünkü yöneticilik sistemi yerine, soruları silme, düzenleme gibi işlemleri belirli bir yetkinliğe erişmiş kullanıcılar tarafından yapılabilmesi üzerine bir konsept düşünüyoruz.

Bununla ilgili çalışmalar yapılacak, fakat henüz bunları konuşmak için erken diye düşünüyorum. Ayrıca [backend](https://github.com/sokrates/server) tarafını da inceleyebilirsin.

Zamanı geldiğinde buradaki özellikler tartışılarak, yeni versiyonlarda çıkarılabilir.
